[versions]
ktor = "1.3.1"

[plugins]
korge = { id = "com.soywiz.korge", version = "5.0.6" }
#korge = { id = "com.soywiz.korge", version = "999.0.0.999" }

[libraries]
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
logback = { "module" = "ch.qos.logback:logback-classic", version="1.2.3" }

